//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WebApiHPUVEC.ArgoBasicService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ArgoServiceSoapBinding", Namespace="http://www.navis.com/services/argoservice")]
    public partial class ArgoService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback genericInvokeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ArgoService() {
            this.Url = global::WebApiHPUVEC.Properties.Settings.Default.WebApiHPUVEC_ArgoBasicService_ArgoService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event genericInvokeCompletedEventHandler genericInvokeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("genericInvokeResponse", Namespace="http://www.navis.com/services/argoservice")]
        public genericInvokeResponse genericInvoke([System.Xml.Serialization.XmlElementAttribute("genericInvoke", Namespace="http://www.navis.com/services/argoservice")] genericInvoke genericInvoke1) {
            object[] results = this.Invoke("genericInvoke", new object[] {
                        genericInvoke1});
            return ((genericInvokeResponse)(results[0]));
        }
        
        /// <remarks/>
        public void genericInvokeAsync(genericInvoke genericInvoke1) {
            this.genericInvokeAsync(genericInvoke1, null);
        }
        
        /// <remarks/>
        public void genericInvokeAsync(genericInvoke genericInvoke1, object userState) {
            if ((this.genericInvokeOperationCompleted == null)) {
                this.genericInvokeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngenericInvokeOperationCompleted);
            }
            this.InvokeAsync("genericInvoke", new object[] {
                        genericInvoke1}, this.genericInvokeOperationCompleted, userState);
        }
        
        private void OngenericInvokeOperationCompleted(object arg) {
            if ((this.genericInvokeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.genericInvokeCompleted(this, new genericInvokeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.navis.com/services/argoservice")]
    public partial class genericInvoke {
        
        private ScopeCoordinateIdsWsType scopeCoordinateIdsWsTypeField;
        
        private string xmlDocField;
        
        /// <remarks/>
        public ScopeCoordinateIdsWsType scopeCoordinateIdsWsType {
            get {
                return this.scopeCoordinateIdsWsTypeField;
            }
            set {
                this.scopeCoordinateIdsWsTypeField = value;
            }
        }
        
        /// <remarks/>
        public string xmlDoc {
            get {
                return this.xmlDocField;
            }
            set {
                this.xmlDocField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://types.webservice.argo.navis.com/v1.0")]
    public partial class ScopeCoordinateIdsWsType {
        
        private string operatorIdField;
        
        private string complexIdField;
        
        private string facilityIdField;
        
        private string yardIdField;
        
        private string externalUserIdField;
        
        /// <remarks/>
        public string operatorId {
            get {
                return this.operatorIdField;
            }
            set {
                this.operatorIdField = value;
            }
        }
        
        /// <remarks/>
        public string complexId {
            get {
                return this.complexIdField;
            }
            set {
                this.complexIdField = value;
            }
        }
        
        /// <remarks/>
        public string facilityId {
            get {
                return this.facilityIdField;
            }
            set {
                this.facilityIdField = value;
            }
        }
        
        /// <remarks/>
        public string yardId {
            get {
                return this.yardIdField;
            }
            set {
                this.yardIdField = value;
            }
        }
        
        /// <remarks/>
        public string externalUserId {
            get {
                return this.externalUserIdField;
            }
            set {
                this.externalUserIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://types.webservice.argo.navis.com/v1.0")]
    public partial class QueryResultType {
        
        private string resultField;
        
        /// <remarks/>
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://types.webservice.argo.navis.com/v1.0")]
    public partial class MessageType {
        
        private string messageField;
        
        private string severityLevelField;
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string SeverityLevel {
            get {
                return this.severityLevelField;
            }
            set {
                this.severityLevelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://types.webservice.argo.navis.com/v1.0")]
    public partial class ResponseType {
        
        private string statusField;
        
        private string statusDescriptionField;
        
        private MessageType[] messageCollectorField;
        
        private QueryResultType[] queryResultsField;
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string StatusDescription {
            get {
                return this.statusDescriptionField;
            }
            set {
                this.statusDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Messages", IsNullable=false)]
        public MessageType[] MessageCollector {
            get {
                return this.messageCollectorField;
            }
            set {
                this.messageCollectorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("QueryResults")]
        public QueryResultType[] QueryResults {
            get {
                return this.queryResultsField;
            }
            set {
                this.queryResultsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://types.webservice.argo.navis.com/v1.0")]
    public partial class GenericInvokeResponseWsType {
        
        private ResponseType commonResponseField;
        
        private string statusField;
        
        private string responsePayLoadField;
        
        /// <remarks/>
        public ResponseType commonResponse {
            get {
                return this.commonResponseField;
            }
            set {
                this.commonResponseField = value;
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string responsePayLoad {
            get {
                return this.responsePayLoadField;
            }
            set {
                this.responsePayLoadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.navis.com/services/argoservice")]
    public partial class genericInvokeResponse {
        
        private GenericInvokeResponseWsType genericInvokeResponse1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("genericInvokeResponse")]
        public GenericInvokeResponseWsType genericInvokeResponse1 {
            get {
                return this.genericInvokeResponse1Field;
            }
            set {
                this.genericInvokeResponse1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void genericInvokeCompletedEventHandler(object sender, genericInvokeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class genericInvokeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal genericInvokeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public genericInvokeResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((genericInvokeResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591